/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zwg_tentcondemo_utils_NDKtest */

#ifndef _Included_com_zwg_tentcondemo_utils_NDKtest
#define _Included_com_zwg_tentcondemo_utils_NDKtest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zwg_tentcondemo_utils_NDKtest
 * Method:    getJNIString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zwg_tentcondemo_utils_NDKtest_getJNIString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
